### ISSUE TITLE
친구 추가 api 요청시 csrf 정보 추가 필요

### ISSUE THREAD

**Issue by ued123** [ued123/talk-about-anything#30]
![image](https://github.com/ued123/talk-about-anything/assets/32861341/1d4bf452-e3a2-4810-8045-92b0ff2b9127)

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu May 25 06:36:03 KST 2023
There was an unexpected error (type=Method Not Allowed, status=405).
Method 'GET' is not supported.
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' is not supported
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:265)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:441)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:382)

**Comment by ued123** [comment]
기본으로 csrf 보호정책을 스프링 security 4.0 이상 버전에서 제공해준다고 함
**예시) 템플릿 엔진타입리프를 사용한다고 하면 기본으로 타입리프에서 아래와 같이 불러올수 있음**

```html
<meta name="_csrf" th:content="${_csrf.token}"/>
<meta name="_csrf_header" th:content="${_csrf.headerName}"/>
```
